### ISSUE TITLE
Building library from source errors out

### ISSUE THREAD

**Issue by mgiammar** [deepanshs/mrsimulator#137]
Did you find a bug? Please help us improve by fill out the sections below. 👍

**Describe the bug**

Running `pip install -e .` results in a long error relating to the file `/pyproject.toml`:
```
Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/mgiammar/opt/anaconda3/envs/mrsimulator-dev/bin/python /Users/mgiammar/opt/anaconda3/envs/mrsimulator-dev/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/rx/hp_ntm7x7vxfstm8twywpgdw0000gn/T/tmp6n7cyehk
         cwd: /Users/mgiammar/Documents/Python/mrsimulator
    Complete output (526 lines):
    Using python version 3.9.2
    mrsimulator version  0.7.0rc1
    Attempting to link mrsimulator with the openblas library.
    Attempting to link mrsimulator with the fftw library.
    ['/opt/homebrew/opt/openblas/include', '/usr/local/opt/openblas/include', '/usr/local/opt/fftw/include', '/opt/homebrew/opt/fftw/include', 'src/c_lib/include/', '/private/var/folders/rx/hp_ntm7x7vxfstm8twywpgdw0000gn/T/pip-build-env-s5k_069j/overlay/lib/python3.9/site-packages/numpy/core/include']
    ['/usr/local/opt/fftw/lib', '/opt/homebrew/opt/openblas/lib', '/opt/homebrew/opt/fftw/lib', '/usr/local/opt/openblas/lib']
    ['fftw3', 'openblas']
    ['-O3', '-fvectorize', '-fcommon', '-ffast-math', '-DUSE_OPENBLAS']
    ['-lm']
    /private/var/folders/rx/hp_ntm7x7vxfstm8twywpgdw0000gn/T/pip-build-env-s5k_069j/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:100: _ExperimentalProjectMetadata: Support for project metadata in `pyproject.toml` is still experimental and may be removed (or change) in future releases.
      warnings.warn(msg, _ExperimentalProjectMetadata)
    configuration error: `project` must contain ['name'] properties
    DESCRIPTION:
        Data structure for the **project** table inside ``pyproject.toml`` (as
        initially defined in :pep:`621`)
    
    GIVEN VALUE:
        {
            "requires-python": ">=3.6"
        }
    
    OFFENDING RULE: 'required'
    
    DEFINITION:
        {
            "$schema": "http://json-schema.org/draft-07/schema",
            "$id": "https://packaging.python.org/en/latest/specifications/declaring-project-metadata/",
            "title": "Package metadata stored in the ``project`` table",
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The name (primary identifier) of the project. MUST be statically defined.",
                    "format": "pep508-identifier"
                },
                "version": {
                    "type": "string",
                    "description": "The version of the project as supported by :pep:`440`.",
                    "format": "pep440"
                },
                "description": {
                    "type": "string",
                    "$$description": [
                        "The `summary description of the project",
                        "<https://packaging.python.org/specifications/core-metadata/#summary>`_"
                    ]
                },
                "readme": {
                    "$$description": [
                        "`Full/detailed description of the project in the form of a README",
                        "<https://www.python.org/dev/peps/pep-0621/#readme>`_",
                        "with meaning similar to the one defined in `core metadata's Description",
                        "<https://packaging.python.org/specifications/core-metadata/#description>`_"
                    ],
                    "oneOf": [
                        {
                            "type": "string",
                            "$$description": [
                                "Relative path to a text file (UTF-8) containing the full description",
                                "of the project. If the file path ends in case-insensitive ``.md`` or",
                                "``.rst`` suffixes, then the content-type is respectively",
                                "``text/markdown`` or ``text/x-rst``"
                            ]
                        },
                        {
                            "type": "object",
                            "allOf": [
                                {
                                    "anyOf": [
                                        {
                                            "properties": {
                                                "file": {
                                                    "type": "string",
                                                    "$$description": [
                                                        "Relative path to a text file containing the full description",
                                                        "of the project."
                                                    ]
                                                }
                                            },
                                            "required": [
                                                "file"
                                            ]
                                        },
                                        {
                                            "properties": {
                                                "text": {
                                                    "type": "string",
                                                    "description": "Full text describing the project."
                                                }
                                            },
                                            "required": [
                                                "text"
                                            ]
                                        }
                                    ]
                                },
                                {
                                    "properties": {
                                        "content-type": {
                                            "type": "string",
                                            "$$description": [
                                                "Content-type (:rfc:`1341`) of the full description",
                                                "(e.g. ``text/markdown``). The ``charset`` parameter is assumed",
                                                "UTF-8 when not present."
                                            ],
                                            "$comment": "TODO: add regex pattern or format?"
                                        }
                                    },
                                    "required": [
                                        "content-type"
                                    ]
                                }
                            ]
                        }
                    ]
                },
                "requires-python": {
                    "type": "string",
                    "format": "pep508-versionspec",
                    "$$description": [
                        "`The Python version requirements of the project",
                        "<https://packaging.python.org/specifications/core-metadata/#requires-python>`_."
                    ]
                },
                "license": {
                    "description": "`Project license <https://www.python.org/dev/peps/pep-0621/#license>`_.",
                    "oneOf": [
                        {
                            "properties": {
                                "file": {
                                    "type": "string",
                                    "$$description": [
                                        "Relative path to the file (UTF-8) which contains the license for the",
                                        "project."
                                    ]
                                }
                            },
                            "required": [
                                "file"
                            ]
                        },
                        {
                            "properties": {
                                "text": {
                                    "type": "string",
                                    "$$description": [
                                        "The license of the project whose meaning is that of the",
                                        "`License field from the core metadata",
                                        "<https://packaging.python.org/specifications/core-metadata/#license>`_."
                                    ]
                                }
                            },
                            "required": [
                                "text"
                            ]
                        }
                    ]
                },
                "authors": {
                    "type": "array",
                    "items": {
                        "$id": "#/definitions/author",
                        "title": "Author or Maintainer",
                        "$comment": "https://www.python.org/dev/peps/pep-0621/#authors-maintainers",
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "$$description": [
                                    "MUST be a valid email name, i.e. whatever can be put as a name, before an",
                                    "email, in :rfc:`822`."
                                ]
                            },
                            "email": {
                                "type": "string",
                                "format": "idn-email",
                                "description": "MUST be a valid email address"
                            }
                        }
                    },
                    "$$description": [
                        "The people or organizations considered to be the 'authors' of the project.",
                        "The exact meaning is open to interpretation (e.g. original or primary authors,",
                        "current maintainers, or owners of the package)."
                    ]
                },
                "maintainers": {
                    "type": "array",
                    "items": {
                        "$id": "#/definitions/author",
                        "title": "Author or Maintainer",
                        "$comment": "https://www.python.org/dev/peps/pep-0621/#authors-maintainers",
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string",
                                "$$description": [
                                    "MUST be a valid email name, i.e. whatever can be put as a name, before an",
                                    "email, in :rfc:`822`."
                                ]
                            },
                            "email": {
                                "type": "string",
                                "format": "idn-email",
                                "description": "MUST be a valid email address"
                            }
                        }
                    },
                    "$$description": [
                        "The people or organizations considered to be the 'maintainers' of the project.",
                        "Similarly to ``authors``, the exact meaning is open to interpretation."
                    ]
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "description": "List of keywords to assist searching for the distribution in a larger catalog."
                },
                "classifiers": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "trove-classifier",
                        "description": "`PyPI classifier <https://pypi.org/classifiers/>`_."
                    },
                    "$$description": [
                        "`Trove classifiers <https://pypi.org/classifiers/>`_",
                        "which apply to the project."
                    ]
                },
                "urls": {
                    "type": "object",
                    "description": "URLs associated with the project in the form ``label => value``.",
                    "additionalProperties": false,
                    "patternProperties": {
                        "^.+$": {
                            "type": "string",
                            "format": "url"
                        }
                    }
                },
                "scripts": {
                    "$id": "#/definitions/entry-point-group",
                    "title": "Entry-points",
                    "type": "object",
                    "$$description": [
                        "Entry-points are grouped together to indicate what sort of capabilities they",
                        "provide.",
                        "See the `packaging guides",
                        "<https://packaging.python.org/specifications/entry-points/>`_",
                        "and `setuptools docs",
                        "<https://setuptools.pypa.io/en/latest/userguide/entry_point.html>`_",
                        "for more information."
                    ],
                    "propertyNames": {
                        "format": "python-entrypoint-name"
                    },
                    "additionalProperties": false,
                    "patternProperties": {
                        "^.+$": {
                            "type": "string",
                            "$$description": [
                                "Reference to a Python object. It is either in the form",
                                "``importable.module``, or ``importable.module:object.attr``."
                            ],
                            "format": "python-entrypoint-reference",
                            "$comment": "https://packaging.python.org/specifications/entry-points/"
                        }
                    }
                },
                "gui-scripts": {
                    "$id": "#/definitions/entry-point-group",
                    "title": "Entry-points",
                    "type": "object",
                    "$$description": [
                        "Entry-points are grouped together to indicate what sort of capabilities they",
                        "provide.",
                        "See the `packaging guides",
                        "<https://packaging.python.org/specifications/entry-points/>`_",
                        "and `setuptools docs",
                        "<https://setuptools.pypa.io/en/latest/userguide/entry_point.html>`_",
                        "for more information."
                    ],
                    "propertyNames": {
                        "format": "python-entrypoint-name"
                    },
                    "additionalProperties": false,
                    "patternProperties": {
                        "^.+$": {
                            "type": "string",
                            "$$description": [
                                "Reference to a Python object. It is either in the form",
                                "``importable.module``, or ``importable.module:object.attr``."
                            ],
                            "format": "python-entrypoint-reference",
                            "$comment": "https://packaging.python.org/specifications/entry-points/"
                        }
                    }
                },
                "entry-points": {
                    "$$description": [
                        "Instruct the installer to expose the given modules/functions via",
                        "``entry-point`` discovery mechanism (useful for plugins).",
                        "More information available in the `Python packaging guide",
                        "<https://packaging.python.org/specifications/entry-points/>`_."
                    ],
                    "propertyNames": {
                        "format": "python-entrypoint-group"
                    },
                    "additionalProperties": false,
                    "patternProperties": {
                        "^.+$": {
                            "$id": "#/definitions/entry-point-group",
                            "title": "Entry-points",
                            "type": "object",
                            "$$description": [
                                "Entry-points are grouped together to indicate what sort of capabilities they",
                                "provide.",
                                "See the `packaging guides",
                                "<https://packaging.python.org/specifications/entry-points/>`_",
                                "and `setuptools docs",
                                "<https://setuptools.pypa.io/en/latest/userguide/entry_point.html>`_",
                                "for more information."
                            ],
                            "propertyNames": {
                                "format": "python-entrypoint-name"
                            },
                            "additionalProperties": false,
                            "patternProperties": {
                                "^.+$": {
                                    "type": "string",
                                    "$$description": [
                                        "Reference to a Python object. It is either in the form",
                                        "``importable.module``, or ``importable.module:object.attr``."
                                    ],
                                    "format": "python-entrypoint-reference",
                                    "$comment": "https://packaging.python.org/specifications/entry-points/"
                                }
                            }
                        }
                    }
                },
                "dependencies": {
                    "type": "array",
                    "description": "Project (mandatory) dependencies.",
                    "items": {
                        "$id": "#/definitions/dependency",
                        "title": "Dependency",
                        "type": "string",
                        "description": "Project dependency specification according to PEP 508",
                        "format": "pep508"
                    }
                },
                "optional-dependencies": {
                    "type": "object",
                    "description": "Optional dependency for the project",
                    "propertyNames": {
                        "format": "pep508-identifier"
                    },
                    "additionalProperties": false,
                    "patternProperties": {
                        "^.+$": {
                            "type": "array",
                            "items": {
                                "$id": "#/definitions/dependency",
                                "title": "Dependency",
                                "type": "string",
                                "description": "Project dependency specification according to PEP 508",
                                "format": "pep508"
                            }
                        }
                    }
                },
                "dynamic": {
                    "type": "array",
                    "$$description": [
                        "Specifies which fields are intentionally unspecified and expected to be",
                        "dynamically provided by build tools"
                    ],
                    "items": {
                        "enum": [
                            "version",
                            "description",
                            "readme",
                            "requires-python",
                            "license",
                            "authors",
                            "maintainers",
                            "keywords",
                            "classifiers",
                            "urls",
                            "scripts",
                            "gui-scripts",
                            "entry-points",
                            "dependencies",
                            "optional-dependencies"
                        ]
                    }
                }
            },
            "required": [
                "name"
            ],
            "additionalProperties": false,
            "if": {
                "not": {
                    "required": [
                        "version"
                    ],
                    "$$description": [
                        "version is statically defined in the ``version`` field"
                    ]
                },
                "$$comment": [
                    "According to :pep:`621`:",
                    "    If the core metadata specification lists a field as \"Required\", then",
                    "    the metadata MUST specify the field statically or list it in dynamic",
                    "In turn, `core metadata`_ defines:",
                    "    The required fields are: Metadata-Version, Name, Version.",
                    "    All the other fields are optional.",
                    "Since ``Metadata-Version`` is defined by the build back-end, ``name`` and",
                    "``version`` are the only mandatory information in ``pyproject.toml``.",
                    ".. _core metadata: https://packaging.python.org/specifications/core-metadata/"
                ]
            },
            "then": {
                "properties": {
                    "dynamic": {
                        "contains": {
                            "const": "version"
                        },
                        "$$description": [
                            "version should be listed in ``dynamic``"
                        ]
                    }
                }
            },
            "definitions": {
                "author": {
                    "$id": "#/definitions/author",
                    "title": "Author or Maintainer",
                    "$comment": "https://www.python.org/dev/peps/pep-0621/#authors-maintainers",
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string",
                            "$$description": [
                                "MUST be a valid email name, i.e. whatever can be put as a name, before an",
                                "email, in :rfc:`822`."
                            ]
                        },
                        "email": {
                            "type": "string",
                            "format": "idn-email",
                            "description": "MUST be a valid email address"
                        }
                    }
                },
                "entry-point-group": {
                    "$id": "#/definitions/entry-point-group",
                    "title": "Entry-points",
                    "type": "object",
                    "$$description": [
                        "Entry-points are grouped together to indicate what sort of capabilities they",
                        "provide.",
                        "See the `packaging guides",
                        "<https://packaging.python.org/specifications/entry-points/>`_",
                        "and `setuptools docs",
                        "<https://setuptools.pypa.io/en/latest/userguide/entry_point.html>`_",
                        "for more information."
                    ],
                    "propertyNames": {
                        "format": "python-entrypoint-name"
                    },
                    "additionalProperties": false,
                    "patternProperties": {
                        "^.+$": {
                            "type": "string",
                            "$$description": [
                                "Reference to a Python object. It is either in the form",
                                "``importable.module``, or ``importable.module:object.attr``."
                            ],
                            "format": "python-entrypoint-reference",
                            "$comment": "https://packaging.python.org/specifications/entry-points/"
                        }
                    }
                },
                "dependency": {
                    "$id": "#/definitions/dependency",
                    "title": "Dependency",
                    "type": "string",
                    "description": "Project dependency specification according to PEP 508",
                    "format": "pep508"
                }
            }
        }
    Traceback (most recent call last):
      File "/Users/mgiammar/opt/anaconda3/envs/mrsimulator-dev/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/Users/mgiammar/opt/anaconda3/envs/mrsimulator-dev/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/mgiammar/opt/anaconda3/envs/mrsimulator-dev/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/rx/hp_ntm7x7vxfstm8twywpgdw0000gn/T/pip-build-env-s5k_069j/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/private/var/folders/rx/hp_ntm7x7vxfstm8twywpgdw0000gn/T/pip-build-env-s5k_069j/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/private/var/folders/rx/hp_ntm7x7vxfstm8twywpgdw0000gn/T/pip-build-env-s5k_069j/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 409, in <module>
        setup(
      File "/private/var/folders/rx/hp_ntm7x7vxfstm8twywpgdw0000gn/T/pip-build-env-s5k_069j/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 79, in setup
        return distutils.core.setup(**attrs)
      File "/private/var/folders/rx/hp_ntm7x7vxfstm8twywpgdw0000gn/T/pip-build-env-s5k_069j/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 122, in setup
        dist.parse_config_files()
      File "/private/var/folders/rx/hp_ntm7x7vxfstm8twywpgdw0000gn/T/pip-build-env-s5k_069j/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 836, in parse_config_files
        pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
      File "/private/var/folders/rx/hp_ntm7x7vxfstm8twywpgdw0000gn/T/pip-build-env-s5k_069j/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 52, in apply_configuration
        config = read_configuration(filepath, True, ignore_option_errors, dist)
      File "/private/var/folders/rx/hp_ntm7x7vxfstm8twywpgdw0000gn/T/pip-build-env-s5k_069j/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 117, in read_configuration
        validate(subset, filepath)
      File "/private/var/folders/rx/hp_ntm7x7vxfstm8twywpgdw0000gn/T/pip-build-env-s5k_069j/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 43, in validate
        raise error from None
    ValueError: invalid pyproject.toml config: `project`
    ----------------------------------------
WARNING: Discarding file:///Users/mgiammar/Documents/Python/mrsimulator. Command errored out with exit status 1: /Users/mgiammar/opt/anaconda3/envs/mrsimulator-dev/bin/python /Users/mgiammar/opt/anaconda3/envs/mrsimulator-dev/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/rx/hp_ntm7x7vxfstm8twywpgdw0000gn/T/tmp6n7cyehk Check the logs for full command output.
ERROR: Command errored out with exit status 1: /Users/mgiammar/opt/anaconda3/envs/mrsimulator-dev/bin/python /Users/mgiammar/opt/anaconda3/envs/mrsimulator-dev/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/rx/hp_ntm7x7vxfstm8twywpgdw0000gn/T/tmp6n7cyehk Check the logs for full command output.
```

**To Reproduce**

1. `pip uninstall mrsimulator`
2. `rm -rf build`
3. `pip install -e .`

**Expected behavior**

Mrsimulator is built from source.

**Screenshots**

**Desktop (please complete the following information):**

- OS: [macOS intel (accelerate) and M1 (BLAS)]

- Python version: [3.9.2]
- `mrsimulator` version: [0.7rc1]

**Additional context**

**Comment by mgiammar** [comment]
Changing the first lines of `pyporject.toml` from

```
[project]
requires-python = ">=3.6"
```

to

```
[project]
name = "mrsimulator"
requires-python = ">=3.6"
```

resolves the error.

This seems to come from a new [PEP 621](https://peps.python.org/pep-0621/). However, I'm unsure why this error is only appearing now.
