### ISSUE TITLE
Install problem on Anaconda

### ISSUE THREAD

**Issue by MHFrey** [deepanshs/mrsimulator#377]
Did you find a bug? Please help us improve by fill out the sections below. 👍

**Describe the bug**
I reinstalled Anaconda version Anaconda3-2024.06-1-Windows-x86_64.
When I try to install mrsimulator the install crashes.

**To Reproduce**
Install Anaconda
Start Anaconda NAvigator
Open CMD.exe Prompt
type pip install mrsimulator
the install crashes, see out put below.

- OS: [e.g. macOS]
Windows 10
- Python version: [e.g. 3.12.1]
Python 3.12.4
- `mrsimulator` version: [e.g. 0.3]
- 0.70

(base) C:\Users\frey>pip install mrsimulator
Collecting mrsimulator
  Using cached mrsimulator-0.7.0.tar.gz (337 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\frey\AppData\Local\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\frey\AppData\Local\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\frey\AppData\Local\anaconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\frey\AppData\Local\Temp\pip-build-env-7zeisoby\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\frey\AppData\Local\Temp\pip-build-env-7zeisoby\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\frey\AppData\Local\Temp\pip-build-env-7zeisoby\overlay\Lib\site-packages\setuptools\build_meta.py", line 503, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\frey\AppData\Local\Temp\pip-build-env-7zeisoby\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 14, in <module>
      ModuleNotFoundError: No module named 'numpy.distutils'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by deepanshs** [comment]
Hi,

mrsimulator v0.7 supports build for py3.10 and lower. You are using 3.12. I recommend creating a conda env for python 3.10 and installing it there. 

You can create a conda env with
`conda create -n mrsim_env python=3.10`
then activate the env using
`conda activate mrsim_env`
Now install mrsimulator.

Please let know if you find other bug. Happy to assist.

Best,
-Deepansh

**Comment by MHFrey** [comment]
That fixed the problem.  Thank you.
